### ISSUE TITLE
Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by brianehlert** [shashiu/meshblu-exchange#1]
brian@BrianEhUbu:~/meshblu-exchange$ node command.js 
Cannot read property 'split' of undefined
TypeError: Cannot read property 'split' of undefined
    at MSExchange.autoDiscover (/home/brian/meshblu-exchange/node_modules/ews/lib/msexchange.js:131:50)
    at Plugin.setupEws (/home/brian/meshblu-exchange/index.js:77:17)
    at Plugin.setOptions (/home/brian/meshblu-exchange/index.js:58:8)
    at Socket.<anonymous> (/home/brian/meshblu-exchange/connector.js:26:14)
    at Socket.onack (/home/brian/meshblu-exchange/node_modules/meshblu/node_modules/socket.io-client/lib/socket.js:295:6)
    at Socket.onpacket (/home/brian/meshblu-exchange/node_modules/meshblu/node_modules/socket.io-client/lib/socket.js:220:12)
    at Manager.<anonymous> (/home/brian/meshblu-exchange/node_modules/meshblu/node_modules/socket.io-client/node_modules/component-bind/index.js:21:15)
    at Manager.Emitter.emit (/home/brian/meshblu-exchange/node_modules/meshblu/node_modules/socket.io-client/node_modules/component-emitter/index.js:134:20)
    at Manager.ondecoded (/home/brian/meshblu-exchange/node_modules/meshblu/node_modules/socket.io-client/lib/manager.js:301:8)
    at Decoder.<anonymous> (/home/brian/meshblu-exchange/node_modules/meshblu/node_modules/socket.io-client/node_modules/component-bind/index.js:21:15)

**Comment by brianehlert** [comment]
The workaround to this was to modify the code that created the connection.
The root is that passing the authentication as an environment variable does NOT work.
Using a config file, such as Meshblu.json, and reading it and submitting those variables as the user information does work.
